name: "Lint and Autofix"
description: "Install toolchains, run formatting/linting/autofix, and optionally commit & push fixes"

inputs:
  apply_autofix:
    description: "Whether to apply autofixes (true/false)"
    required: false
    default: "true"
  node-version:
    description: "Node.js version to use"
    required: false
    default: "20"
  python-version:
    description: "Python version to use"
    required: false
    default: "3.11"
  commit-message:
    description: "Commit message for autofix commits"
    required: false
    default: "chore(lint): apply autofixes"
  push:
    description: "Whether to push autofix commits (true/false)"
    required: false
    default: "true"
  push-token:
    description: "Token for pushing commits (prefer AUTOFIX_PUSH_TOKEN secret)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Node.js dependencies
      shell: bash
      run: |
        if [ -f package.json ]; then
          npm ci || npm install
        fi

    - name: Install Python linting tools
      shell: bash
      run: |
        pip install --upgrade pip
        pip install ruff black isort mypy

    - name: Run ESLint (check or fix)
      shell: bash
      run: |
        if [ -f package.json ] && [ -f .eslintrc.cjs ]; then
          if [ "${{ inputs.apply_autofix }}" = "true" ]; then
            npx eslint . --ext .js,.cjs,.mjs --fix || true
          else
            npx eslint . --ext .js,.cjs,.mjs || true
          fi
        fi

    - name: Run Prettier (check or fix)
      shell: bash
      run: |
        if [ -f package.json ] && [ -f .prettierrc ]; then
          if [ "${{ inputs.apply_autofix }}" = "true" ]; then
            npx prettier --write "**/*.{js,cjs,mjs,json,md,yml,yaml}" || true
          else
            npx prettier --check "**/*.{js,cjs,mjs,json,md,yml,yaml}" || true
          fi
        fi

    - name: Run Ruff (check or fix)
      shell: bash
      run: |
        if [ -f pyproject.toml ]; then
          if [ "${{ inputs.apply_autofix }}" = "true" ]; then
            ruff check . --fix || true
          else
            ruff check . || true
          fi
        fi

    - name: Run isort (check or fix)
      shell: bash
      run: |
        if [ -f pyproject.toml ]; then
          if [ "${{ inputs.apply_autofix }}" = "true" ]; then
            isort . || true
          else
            isort . --check-only || true
          fi
        fi

    - name: Run Black (check or fix)
      shell: bash
      run: |
        if [ -f pyproject.toml ]; then
          if [ "${{ inputs.apply_autofix }}" = "true" ]; then
            black . || true
          else
            black . --check || true
          fi
        fi

    - name: Run mypy (check only)
      shell: bash
      run: |
        if [ -f pyproject.toml ]; then
          mypy . --ignore-missing-imports || true
        fi

    - name: Commit and push autofix changes
      if: inputs.apply_autofix == 'true' && inputs.push == 'true'
      shell: bash
      env:
        PUSH_TOKEN: ${{ inputs.push-token }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Check for changes
        if git diff --quiet && git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        fi

        # Stage all changes
        git add -A

        # Commit changes
        git commit -m "${{ inputs.commit-message }}" || echo "Nothing to commit"

        # Push changes using provided token or default GITHUB_TOKEN
        if [ -n "$PUSH_TOKEN" ]; then
          git remote set-url origin "https://x-access-token:${PUSH_TOKEN}@github.com/${{ github.repository }}.git"
        fi

        git push || echo "Push failed - check token permissions"
